apiVersion: v1
kind: ServiceAccount
metadata:
  name: wu-service-account  # Name of your service account
  namespace: test  # Replace with your namespace if needed
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXX:role/role1
